development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:bf2b8643ecb18e9526bebfa69f8cdaeb@pike.redistogo.com:9788/
  # channel_prefix: emissary_api_production
